name: Build And Test

on: push

jobs:
  build:
    if: github.repository_owner == 'bitpatty'
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.4.0'
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: dist
          retention-days: 1
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        node:
          - '16.0.0' # Min supported version
          - '18.12.1' # Max supported version
        typescript:
          - '4.3.2' # Min supported version
          - '4.8.4' # Max supported version
        modulekind:
          - 'es2015'
          - 'es2020'
        scriptversion:
          - 'es2015'
          - 'es2020'
    env:
      JEST_TS_MODULE_KIND: ${{ matrix.modulekind }}
      JEST_TS_SCRIPT_TARGET: ${{ matrix.scriptversion }}
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: dist
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: rm -rf node_modules
      - run: rm package.json
      - run: rm package-lock.json
      - run: |
          npm install \
            typescript@${{ matrix.typescript }} \
            @typescript/vfs \
            @types/node \
            @types/jest \
            ts-jest \
            ts-patch \
            ts-node \
            tslib
      - run: cat package.json
      - run: npx jest --verbose --runInBand --coverage
